# Generated by Django 4.1.7 on 2023-03-22 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(default=None, max_length=200, null=True)),
                ('reporter_name', models.CharField(default=None, max_length=150, null=True)),
                ('incident_details', models.TextField(default=None, null=True)),
                ('reported_date', models.DateField(null=True)),
                ('priority', models.CharField(default=None, max_length=150, null=True)),
                ('incident_status', models.CharField(default=None, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userincident.incident')),
            ],
        ),
    ]
